exclude: '^tests'
repos:
  - repo: https://github.com/hakancelikdev/unimport
    rev: 1.2.1
    hooks:
      - id: unimport
        args:
          ['--remove', '--check', '--include-star-import']
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"]
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.12
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: pretty-format-json
        args: [--autofix]
      - id: trailing-whitespace
        language: python
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports"]
        additional_dependencies:
          - pandas-stubs
          - types-PyYAML==6.0.1
          - types-requests==2.26.3
          - types-setuptools==57.4.5
          - types-Jinja2>=2.11.9
          - types-toml>=0.10.3
          - typed-ast>=1.5.2
          - types-pkg-resources>=0.1.3
          - pydantic>=1.9.0
  - repo: https://github.com/conorfalvey/check_pdb_hook
    rev: 0.0.9
    hooks:
      - id: check_pdb_hook
        pass_filenames: false
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.13
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        args: [--fail-under=100, --verbose]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.7
    hooks:
    -   id: bandit
        args: [-lll, --recursive, clumper]
