site_name: "Multiparser: Parallel File Parsing"
repo_name: GitHub
repo_url: https://github.com/ukaea/multiparser
site_description: Documentation for the Multiparser parallel parsing module
site_url: https://ukaea.github.io/multiparser
markdown_extensions:
  - admonition
  - md_in_html
  - attr_list
  - pymdownx.details
  - pymdownx.betterem
  - pymdownx.superfences:
      custom_fences:
        - class: mermaid
          format: !!python/name:mermaid2.fence.fence_mermaid ""
          name: mermaid
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: "#"
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      social_url_shortener: true
      normalize_issue_symbols: true
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - How it Works: how_it_works.md
    - Basic Example: basic_example.md
  - Concepts:
    - Parsing Types: tracking_and_tailing.md
    - Built-in Parsers: builtin_parsers.md
    - Custom Parsers: custom_parsers.md
  - Development:
    - Contributing: development.md
  - Reference:
    - File Monitor:
      - file_monitor.md
      - tracking.md
      - tailing.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            members_order: source
            separate_signature: true
            filters: ["!^_"]
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
  - git-revision-date-localized:
      fallback_to_build_date: true
      type: date
  - mike:
      # These fields are all optional; the defaults are as below...
      alias_type: symlink
      redirect_template: null
      deploy_prefix: ''
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js
  - mermaid2
site_description: Lessons on using the Ansible framework
theme:
  name: material
  favicon: media/logo_2.png
  logo: media/logo_2.png
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - announce.dismiss
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - search.suggest
    - navigation.footer
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra:
  version:
    provider: mike
