name: multiparser
on: [push]
jobs:
  unit_tests:
    name: Unit Tests (${{ matrix.os }} Python${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [ '3.10', '3.11', '3.12' ]
        experimental: [false]
        include:
          - os: ubuntu-latest
            experimental: true
            python-version: '3.13-dev'

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install Poetry
        run: python -m pip install poetry
      - name: Run Unit Tests
        run: |
          poetry install --all-extras
          poetry run pytest
